import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [location, setLocation] = useState('');
  const [data, setData] = useState({});
  const [weather, setWeather] = useState();
  const [ErrorMessange, setErrorMessange] = useState('');
  const [temp, setTemp] = useState();
  const [feel, setFeel] = useState();
  const [wind, setWind] = useState();

  var apiKey = "8ca7e2dc56cc6762826d7af08501be29";
  var lang = "fr";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`
  console.log(url);

  const searchLocation = (event) => {
    if(event.key === "Enter"){
      axios.get(url)
      .then((response) => {
        console.clear();
        setData(response.data)
        console.log(response.data);
        setWeather(response.data.weather);
        setTemp(response.data.main.temp);
        setFeel(response.data.main.feels_like);
        setWind(response.data.wind.gust);
        setErrorMessange("")
      }).catch(err => {
        console.log(err);
        setErrorMessange("Please enter another location");
        setData({});
        setWeather();
        setTemp();
        setFeel();
        setWind();
      })
      setLocation('')
    }
  }

  return (
    <>
      <Head>
        <title>Week 03 Weather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {ErrorMessange}
        {data.name}
        <input 
          value={location}
          onChange={event => setLocation(event.target.value)}
          placeholder="Enter Location"
          onKeyDown={searchLocation}
          type="text"
        />
        {
          weather && weather.map((w,index)=> {
            return(
              <div key={index}>
                <div>{w.description}</div>
                <div>{w.main}</div>
              </div>
            )
          })
        }
        <div>
          {temp}
        </div>

        <div>
          {feel}
        </div>

        <div>
          {wind}
        </div>
        
      </main>
    </>
  )
}
